const products = [
    {
        id: 1,
        name: 'Molfix',
        image: '/images/productImages/molfix.png',
        description: 'lorem ipsum dolor',
        price: 89,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        id: 2,
        name: 'Huggies',
        image: '/images/productImages/huggies.jpg',
        description: 'lorem ipsum dolor',
        price: 89,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        id: 3,
        name: 'Kisskids',
        image: '/images/productImages/kisskids.png',
        description: 'lorem ipsum dolor',
        price: 89,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        id: 4,
        name: 'Virony',
        image: '/images/productImages/virony.jpg',
        description: 'lorem ipsum dolor',
        price: 89,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        id: 5,
        name: 'Softrux',
        image: '/images/productImages/softrux.jpg',
        description: 'lorem ipsum dolor',
        price: 89,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        id: 6,
        name: 'Bebem',
        image: '/images/productImages/bebem.jpg',
        description: 'lorem ipsum dolor',
        price: 89,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        id: 7,
        name: 'Anion Sanitory Napkin',
        image: '/images/productImages/anion-sanitary-napkin.jpg',
        description: 'lorem ipsum dolor',
        price: 89,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        id: 8,
        name: 'Sunlit Kitchen Oil Cleaner',
        image: '/images/productImages/sunlit-kitchen.jpg',
        description: 'lorem ipsum dolor',
        price: 89,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        id: 9,
        name: 'Sunlit Body Lotion',
        image: '/images/productImages/sunlit-body-lotion.png',
        description: 'lorem ipsum dolor',
        price: 89,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        id: 10,
        name: 'Sunlit Body Wash & Shampoo',
        image: '/images/productImages/body-wash-and-shampoo.png',
        description: 'lorem ipsum dolor',
        price: 89,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        id: 11,
        name: 'Norland Skin Rejuvenating & Smoothing Toner',
        image: '/images/productImages/norland-skin.png',
        description: 'lorem ipsum dolor',
        price: 89,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        id: 12,
        name: 'Norland Skin Rejuvenating & Moisturizing Milk',
        image: '/images/productImages/moisturizing-milk.png',
        description: 'lorem ipsum dolor',
        price: 89,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        id: 13,
        name: 'Norland Sunlit Antibacterial Ge',
        image: '/images/productImages/sunlit-antibacterial-ge.png',
        description: 'lorem ipsum dolor',
        price: 5000.00,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        id: 14,
        name: 'Norland Non-Linear D-Machine',
        image: '/images/productImages/norland-non-linear-d-machine.png',
        description: 'lorem ipsum dolor',
        price: 2300.00,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        id: 15,
        name: 'Norland Power Bank',
        image: '/images/productImages/norland-power-bank.png',
        description: 'lorem ipsum dolor',
        price: 15000.00,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        id: 16,
        name: 'Norland Power Bank',
        image: '/images/productImages/norland-power-bank.png',
        description: 'lorem ipsum dolor',
        price: 15000.00,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    // {
    //     id: 17,
    //     name: 'Norland Power Bank',
    //     image: '/images/productImages/norland-power-bank.png',
    //     description: 'lorem ipsum dolor',
    //     price: 15000.00,
    //     countInStock: 3,
    //     rating: 4,
    //     numReviews: 4,
    // },
]

export default products